apiVersion: apps/v1
kind: Deployment
metadata:
  name: true-tracker
  namespace: true-tracker
  labels:
    app: true-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: true-tracker
  template:
    metadata:
      labels:
        app: true-tracker
    spec:
      containers:
        - name: true-tracker
          image: "trueberryless/true-tracker:main-568894012f827494d010b3648a57d5234d828d5b"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
